name: Auto Api Task

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
    - cron: '12 */3 * * *'
  watch:
    types: [started]
   
jobs:
  Task:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.17

    - name: Install requests # 安装 requests
      run: pip install requests

    - name: Copy script and set env variables
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }}  # 你的client_id
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} # 你的client_secret
      run: cp 1.py 2.py

    - name: Test Api # 调用API
      env:
        CONFIG_ID: ${{ secrets.CONFIG_ID }}
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
      run: |
        echo "$(date +"%Y-%m-%d %H:%M:%S") begin" > time.log
        python 2.py
    
    - name: Show current directory and files
      run: |
        pwd
        ls -al
    
    - name: Show git status
      run: git status
    
    - name: Commit # 上传新的 refresh_token 到仓库
      run: |
        git config --global user.email "hbzjt2012@foxmail.com"
        git config --global user.name "hbzjt2012"
        git add .
        git status  # 查看暂存区状态，确认添加成功
        git diff --cached --quiet && echo "No changes to commit" || git commit -m "update new refresh_token"

    
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

